bot:
  stickers:
    fromOneUserAtOnce: 1
    atRow: 3
    fromUserPerMinute: 10
    maxStrikersAtRow: 10


spring:
  application:
    name: JosephBot
logging:
  level:
     org.springframework.web: ERROR
     ru.ulmc: DEBUG